"""crear tabla chequeos

Revision ID: 06ed3f4986af
Revises: 840584ec0600
Create Date: 2026-09-23 09:01:13.240663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06ed3f4986af'
down_revision: Union[str, None] = '840584ec0600'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chequeos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sitio_id', sa.Integer(), nullable=False),
    sa.Column('disponible', sa.Boolean(), nullable=False),
    sa.Column('tiempo_respuesta_ms', sa.Integer(), nullable=True),
    sa.Column('codigo_http', sa.Integer(), nullable=True),
    sa.Column('ssl_valido', sa.Boolean(), nullable=True),
    sa.Column('ssl_dias_restantes', sa.Integer(), nullable=True),
    sa.Column('puntaje_pagespeed', sa.Float(), nullable=True),
    sa.Column('ejecutado_en', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sitio_id'], ['sitios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chequeos_id'), 'chequeos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chequeos_id'), table_name='chequeos')
    op.drop_table('chequeos')
    # ### end Alembic commands ###
